### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by micahlmartin** [Datahero/node-pardot#3]
How do you feel about using a promise livrary like  q instead of callbacks?  Also, how are you handling api key expiration?

**Comment by jzabel** [comment]
@micahlmartin  - I'm not a huge fan of q, but think async can help manage nested callbacks well.  For api expiration, we are handling by watching for the error from pardot as follows.  If we get an "Invalid API key", then we attempt to refresh using their email, password and user_key.  This is why we don't use the api_key as you can't really refresh it without an email . . . . 
Example error handling code - hope this helps:

``` javascript
bottomError = error.getBottomPrevError();

  if (bottomError.message.indexOf('Invalid API key') > -1) {
    heroError = new HeroError.ImportServiceAuthorizationFailed('Invalid pardot credentials', error);
  } else if (bottomError.message.indexOf('Client IP address/location must be activated') > -1) {
    heroError = new HeroError.ImportPardotIPAddressActivationNeeded('Client IP address/location must be activated',
      error);
  } else {
    heroError = new HeroError.Internal('Unknown error from pardot', error);
  }
```
